INSERT INTO STATE (LABEL) VALUES ('PRE_COMMITEE');
INSERT INTO STATE (LABEL) VALUES ('IN_COMMITEE');
INSERT INTO STATE (LABEL) VALUES ('FINAL');

INSERT into PACKET (STATE_ID_FK) VALUES  ('1');

INSERT into STATIC_DATA (LABEL) values ('VERY_WEAK');
INSERT into STATIC_DATA (LABEL) values ('WEAK');
INSERT into STATIC_DATA (LABEL) values ('MODERATE');
INSERT into STATIC_DATA (LABEL) values ('ADEQUATE');
INSERT into STATIC_DATA (LABEL) values ('STRONG');
INSERT into STATIC_DATA (LABEL) values ('VERY_STRONG');

INSERT into COMPT (LABEL, PACKET_ID_FK) values ('Risk position with Extraordinary Support', '1');
INSERT into COMPT (LABEL, PACKET_ID_FK) values ('Growth and Changes in Exposure', '1');
INSERT into COMPT (LABEL, PACKET_ID_FK) values ('Risk Concentrations and Risk Diversification', '1');
INSERT into COMPT (LABEL, PACKET_ID_FK) values ('Complexity', '1');
INSERT into COMPT (LABEL, PACKET_ID_FK) values ('Risks not covered by RACF', '1');
INSERT into COMPT (LABEL, PACKET_ID_FK) values ('Evidence of stronger or weaker Loss Experience', '1');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '1', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '1', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '1', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '1', '4', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '1', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '1', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '2', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '2', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '2', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '2', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '2', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '2', '6', 'y');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '3', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '3', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '3', '3', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '3', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '3', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '1', '3', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '1', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '1', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '1', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '1', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '1', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '1', '6', 'y');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '2', '1', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '2', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '2', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '2', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '2', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '2', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '3', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '3', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '3', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '3', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '3', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '2', '3', '6', 'y');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '1', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '1', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '1', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '1', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '1', '5', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '1', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '2', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '2', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '2', '3', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '2', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '2', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '2', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '3', '1', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '3', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '3', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '3', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '3', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '3', '3', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '1', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '1', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '1', '3', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '1', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '1', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '1', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '2', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '2', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '2', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '2', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '2', '5', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '2', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '3', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '3', '2', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '3', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '3', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '3', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '4', '3', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '1', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '1', '2', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '1', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '1', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '1', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '1', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '2', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '2', '2', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '2', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '2', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '2', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '2', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '3', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '3', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '3', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '3', '4', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '3', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '5', '3', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '1', '1', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '1', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '1', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '1', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '1', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '1', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '2', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '2', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '2', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '2', '4', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '2', '5', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '2', '6', 'n');

INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '3', '1', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '3', '2', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '3', '3', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '3', '4', 'n');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '3', '5', 'y');
INSERT into DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, STATIC_DATA_ID_FK, CHECKED) values ( '6', '3', '6', 'n');
