DROP TABLE IF EXISTS `STATE`;
CREATE TABLE `STATE` (
  `STATE_ID` INT(2)      NOT NULL AUTO_INCREMENT,
  `LABEL`    VARCHAR(20) NOT NULL,
  `VERSION`  INT         NOT NULL DEFAULT 0,
  PRIMARY KEY (`STATE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `PACKET`;
CREATE TABLE `PACKET` (
  `PACKET_ID`   INT(11) NOT NULL AUTO_INCREMENT,
  `STATE_ID_FK` INT(2)  NOT NULL,
  `VERSION`     INT     NOT NULL DEFAULT 0,
  PRIMARY KEY (`PACKET_ID`),
  FOREIGN KEY (`STATE_ID_FK`) REFERENCES `STATE` (`STATE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `STATIC_DATA`;
CREATE TABLE `STATIC_DATA` (
  `STATIC_DATA_ID` INT(11)     NOT NULL AUTO_INCREMENT,
  `LABEL`          VARCHAR(20) NOT NULL,
  `VERSION`        INT         NOT NULL DEFAULT 0,
  PRIMARY KEY (`STATIC_DATA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `COMPT`;
CREATE TABLE `COMPT` (
  `COMPT_ID`     INT(11)     NOT NULL AUTO_INCREMENT,
  `LABEL`        VARCHAR(75) NOT NULL,
  `PACKET_ID_FK` INT(11)     NOT NULL,
  `VERSION`      INT         NOT NULL DEFAULT 0,
  PRIMARY KEY (`COMPT_ID`),
  FOREIGN KEY (`PACKET_ID_FK`) REFERENCES `PACKET` (`PACKET_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `DATA_COMPT`;
CREATE TABLE `DATA_COMPT` (
  `DATA_COMPT_ID`     INT(21) NOT NULL AUTO_INCREMENT,
  `COMPT_ID_FK`       INT(11) NOT NULL,
  `STATE_ID_FK`       INT(1)  NOT NULL,
  `STATIC_DATA_ID_FK` int(11) NOT NULL,
  `CHECKED`           CHAR(1) NOT NULL,
  `VERSION`           INT     NOT NULL DEFAULT 0,

  PRIMARY KEY (`DATA_COMPT_ID`),
  FOREIGN KEY (`COMPT_ID_FK`) REFERENCES `COMPT` (`COMPT_ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY (`STATE_ID_FK`) REFERENCES `STATE` (`STATE_ID`),
  FOREIGN KEY (`STATIC_DATA_ID_FK`) REFERENCES `STATIC_DATA` (`STATIC_DATA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;


