DROP TABLE IF EXISTS STATE;
CREATE TABLE STATE (
  STATE_ID INT(2)      NOT NULL AUTO_INCREMENT,
  LABEL    VARCHAR(20) NOT NULL,
  VERSION  INT         NOT NULL DEFAULT 0,
  PRIMARY KEY (STATE_ID)
);
INSERT INTO STATE (LABEL) VALUES ('PRE_COMMITEE');
INSERT INTO STATE (LABEL) VALUES ('IN_COMMITEE');
INSERT INTO STATE (LABEL) VALUES ('FINAL');

DROP TABLE IF EXISTS PACKET;
CREATE TABLE PACKET (
  PACKET_ID   INT(11) NOT NULL AUTO_INCREMENT,
  STATE_ID_FK INT(2)  NOT NULL,
  VERSION     INT     NOT NULL DEFAULT 0,
  PRIMARY KEY (PACKET_ID),
  --   FOREIGN KEY (STATE_ID_FK) REFERENCES STATE (STATE_ID)
);

INSERT INTO PACKET (STATE_ID_FK) VALUES ('1');

DROP TABLE IF EXISTS COMBO_DATA;
CREATE TABLE COMBO_DATA (
  COMBO_DATA_ID INT(11)     NOT NULL   AUTO_INCREMENT,
  LABEL         VARCHAR(20) NOT NULL,
  VERSION       INT         NOT NULL   DEFAULT 0,
  --   UNIQUE UQ_COMBO_DATA_1 (LABEL),
  PRIMARY KEY (COMBO_DATA_ID)
);

INSERT INTO COMBO_DATA (LABEL) VALUES ('VERY_WEAK');
INSERT INTO COMBO_DATA (LABEL) VALUES ('WEAK');
INSERT INTO COMBO_DATA (LABEL) VALUES ('MODERATE');
INSERT INTO COMBO_DATA (LABEL) VALUES ('ADEQUATE');
INSERT INTO COMBO_DATA (LABEL) VALUES ('STRONG');
INSERT INTO COMBO_DATA (LABEL) VALUES ('VERY_STRONG');

DROP TABLE IF EXISTS COMPT;
CREATE TABLE COMPT (
  COMPT_ID     INT(11)     NOT NULL AUTO_INCREMENT,
  LABEL        VARCHAR(75) NOT NULL,
  PACKET_ID_FK INT(11)     NOT NULL,
  VERSION      INT         NOT NULL DEFAULT 0,
  --   UNIQUE UQ_COMPT_1 (PACKET_ID_FK, LABEL),
  PRIMARY KEY (COMPT_ID),
  --   FOREIGN KEY (PACKET_ID_FK) REFERENCES PACKET (PACKET_ID)
);

INSERT INTO COMPT (LABEL, PACKET_ID_FK) VALUES ('Risk position with Extraordinary Support', '1');
INSERT INTO COMPT (LABEL, PACKET_ID_FK) VALUES ('Growth and Changes in Exposure', '1');
INSERT INTO COMPT (LABEL, PACKET_ID_FK) VALUES ('Risk Concentrations and Risk Diversification', '1');
INSERT INTO COMPT (LABEL, PACKET_ID_FK) VALUES ('Complexity', '1');
INSERT INTO COMPT (LABEL, PACKET_ID_FK) VALUES ('Risks not covered by RACF', '1');
INSERT INTO COMPT (LABEL, PACKET_ID_FK) VALUES ('Evidence of stronger or weaker Loss Experience', '1');

DROP TABLE IF EXISTS DATA_COMPT;
CREATE TABLE DATA_COMPT (
  DATA_COMPT_ID    INT(21) NOT NULL AUTO_INCREMENT,
  COMPT_ID_FK      INT(11) NOT NULL,
  STATE_ID_FK      INT(1)  NOT NULL,
  COMBO_DATA_ID_FK INT(11) NOT NULL,
  CHECKED          CHAR(1) NOT NULL,
  VERSION          INT     NOT NULL DEFAULT 0,
  --   UNIQUE UQ_DATA_COMPT_1 (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK),
  PRIMARY KEY (DATA_COMPT_ID),
  --   FOREIGN KEY (COMPT_ID_FK) REFERENCES COMPT (COMPT_ID)
  --   ON DELETE CASCADE
  --   ON UPDATE CASCADE,
  --   FOREIGN KEY (STATE_ID_FK) REFERENCES STATE (STATE_ID),
  --   FOREIGN KEY (COMBO_DATA_ID_FK) REFERENCES COMBO_DATA (COMBO_DATA_ID)
);

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '1', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '1', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '1', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '1', '4', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '1', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '1', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '2', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '2', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '2', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '2', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '2', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '2', '6', 'y');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '3', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '3', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '3', '3', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '3', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '3', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('1', '3', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '1', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '1', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '1', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '1', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '1', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '1', '6', 'y');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '2', '1', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '2', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '2', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '2', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '2', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '2', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '3', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '3', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '3', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '3', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '3', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('2', '3', '6', 'y');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '1', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '1', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '1', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '1', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '1', '5', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '1', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '2', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '2', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '2', '3', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '2', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '2', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '2', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '3', '1', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '3', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '3', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '3', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '3', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('3', '3', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '1', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '1', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '1', '3', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '1', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '1', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '1', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '2', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '2', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '2', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '2', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '2', '5', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '2', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '3', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '3', '2', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '3', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '3', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '3', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('4', '3', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '1', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '1', '2', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '1', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '1', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '1', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '1', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '2', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '2', '2', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '2', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '2', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '2', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '2', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '3', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '3', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '3', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '3', '4', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '3', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('5', '3', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '1', '1', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '1', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '1', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '1', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '1', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '1', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '2', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '2', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '2', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '2', '4', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '2', '5', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '2', '6', 'n');

INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '3', '1', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '3', '2', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '3', '3', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '3', '4', 'n');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '3', '5', 'y');
INSERT INTO DATA_COMPT (COMPT_ID_FK, STATE_ID_FK, COMBO_DATA_ID_FK, CHECKED) VALUES ('6', '3', '6', 'n');
