DROP TABLE IF EXISTS `PACKET`;
CREATE TABLE `PACKET` (
  `PACKET_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATE_ID_FK` int(1) NOT NULL,
  PRIMARY KEY (`PACKET_ID`),
  FOREIGN KEY (`STATE_ID_FK`) REFERENCES `STATE` (`STATE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

insert into PACKET (STATE_ID_FK) VALUES  ('1');


