DROP TABLE IF EXISTS `STATE`;
CREATE TABLE `STATE` (
  `STATE_ID` int(1) NOT NULL AUTO_INCREMENT,
  `LABEL` varchar(20) NOT NULL,
  PRIMARY KEY (`STATE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

insert into STATE (LABEL) values ('PRE_COMMITEE');
insert into STATE (LABEL) values ('IN_COMMITEE');
insert into STATE (LABEL) values ('FINAL');
