DROP TABLE IF EXISTS `STATIC_DATA`;
CREATE TABLE `STATIC_DATA` (
  `STATIC_DATA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LABEL` varchar(20) NOT NULL,
  PRIMARY KEY (`STATIC_DATA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

insert into STATIC_DATA (LABEL) values ('VERY_WEAK');
insert into STATIC_DATA (LABEL) values ('WEAK');
insert into STATIC_DATA (LABEL) values ('MODERATE');
insert into STATIC_DATA (LABEL) values ('ADEQUATE');
insert into STATIC_DATA (LABEL) values ('STRONG');
insert into STATIC_DATA (LABEL) values ('VERY_STRONG');



